
aerial_ship_saml_sp.security.login:
    path: /saml/sp/login
    defaults: { _controller: "AerialShipSamlSPBundle:Security:login" }

aerial_ship_saml_sp.security.acs:
    path: /saml/sp/acs
    defaults: { _controller: "AerialShipSamlSPBundle:Security:check" }

aerial_ship_saml_sp.security.logout:
    path: /saml/sp/logout
    defaults: { _controller: "AerialShipSamlSPBundle:Security:logout" }

aerial_ship_saml_sp.security.failure:
    path: /saml/sp/failure
    defaults: { _controller: "AerialShipSamlSPBundle:Security:failure" }

aerial_ship_saml_sp.security.federation_metadata:
    path: /saml/sp/FederationMetadata.xml
    defaults: { _controller: "AerialShipSamlSPBundle:Security:federationMetadata" }

aerial_ship_saml_sp.security.discovery:
    path: /saml/sp/discovery
    defaults: { _controller: "AerialShipSamlSPBundle:Security:discovery" }
